#!/bin/bash

export DISPLAY=:10

while true; do
    firefox_pid=$(pgrep firefox)
    feelingsurf_pids=$(pgrep FeelingSurfView)
    if [ -n "$firefox_pid" ]; then
        pkill -9 firefox
    fi
    if [ -z "$feelingsurf_pids" ]; then
        FeelingSurfViewer &
    fi
    sleep 5
done
